//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DylansStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public Shipment()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int ShipmentID { get; set; }
        public string TrackingNumber { get; set; }
        public string Carrier { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
